version: 1.0
app:
  version: "fbb0dc1e-aa03-40a1-a84b-10848b46d757"
  instances:
    min: 1
    max: 1
  resources:
    cpu: 1
  env:
    - name: SOME_ENV_VAR_NAME
      value: some_env_var_value
  variables:
    - name: some_liberty_variable_name
      value: some_liberty_variable_value
  systemProperties:
    - name: some_system_property_name
      value: some_system_property_value.
  endpoints: public
  services:
    - crn: 'crn:v1:bluemix:public:mqcloud:us-east:a/26a5e866a11a5014f2eca2acab86f048:123019ac-5871-4f20-8e10-1207b38721fc::'
